import type { JourneyData } from "./types";

export const TODAY_FALLBACK = "2026-08-11";

export function todayISO() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

export const seed: JourneyData = {
  trip: {
    id: "trip-africa-2026",
    name: "AFRICA 2026",
    subtitle: "Kenya escorted journey",
    startDate: "2026-08-05",
    endDate: "2026-08-15",
    description:
      "Eleven unforgettable days across Kenya with Windsong Travel — from Nairobi to the plains of the Maasai Mara, travelling together as one small group.",
  },
  locations: [
    {
      id: "loc-nairobi",
      tripId: "trip-africa-2026",
      name: "Nairobi",
      shortName: "Nairobi",
      description:
        "Kenya's welcoming capital, where our journey begins. Home to the Giraffe Centre and the elephant nursery.",
      lat: -1.2921,
      lng: 36.8219,
      order: 1,
      status: "visited",
      imageKey: "hero",
    },
    {
      id: "loc-olpejeta",
      tripId: "trip-africa-2026",
      name: "Ol Pejeta Conservancy",
      shortName: "Ol Pejeta",
      description:
        "A peaceful conservancy at the foot of Mount Kenya, and home to the last northern white rhinos.",
      lat: 0.0009,
      lng: 36.9,
      order: 2,
      status: "visited",
      imageKey: "elephants",
    },
    {
      id: "loc-samburu",
      tripId: "trip-africa-2026",
      name: "Samburu National Reserve",
      shortName: "Samburu",
      description:
        "Wild red earth and doum palms along the Ewaso Ng'iro river, with rare northern wildlife.",
      lat: 0.6,
      lng: 37.53,
      order: 3,
      status: "visited",
      imageKey: "elephants",
    },
    {
      id: "loc-naivasha",
      tripId: "trip-africa-2026",
      name: "Lake Naivasha",
      shortName: "Lake Naivasha",
      description: "A freshwater lake in the Great Rift Valley, full of hippos, pelicans and fish eagles.",
      lat: -0.7772,
      lng: 36.3606,
      order: 4,
      status: "upcoming",
      imageKey: "balloon",
    },
    {
      id: "loc-mara",
      tripId: "trip-africa-2026",
      name: "Maasai Mara National Reserve",
      shortName: "Maasai Mara",
      description:
        "The great golden plains of the Mara — the finest place in Africa to watch lions, elephants and the great migration.",
      lat: -1.4061,
      lng: 35.0083,
      order: 5,
      status: "upcoming",
      imageKey: "lions",
    },
    {
      id: "loc-camp",
      tripId: "trip-africa-2026",
      name: "Mara Safari Camp",
      shortName: "Safari Camp",
      description: "Our home in the Mara — comfortable tented rooms, a shaded dining terrace and evening fires.",
      lat: -1.4123,
      lng: 35.0197,
      order: 6,
      status: "upcoming",
      imageKey: "hero",
    },
  ],
  days: [
    {
      id: "day-1",
      tripId: "trip-africa-2026",
      date: "2026-08-09",
      title: "Samburu farewell",
      note: "A relaxed morning. Please leave your suitcase outside your room by 8:00 AM.",
    },
    {
      id: "day-2",
      tripId: "trip-africa-2026",
      date: "2026-08-10",
      title: "Travel to the Mara",
      note: "A long but beautiful drive today. We will stop for lunch along the Rift Valley viewpoint.",
    },
    {
      id: "day-today",
      tripId: "trip-africa-2026",
      date: TODAY_FALLBACK,
      title: "Maasai Mara game drives",
      note: "Please bring your water bottle and a light jacket for the morning drive.",
    },
  ],
  items: [
    { id: "it-1", dayId: "day-today", time: "7:00 AM", title: "Morning Game Drive", emoji: "🦁", locationId: "loc-mara" },
    { id: "it-2", dayId: "day-today", time: "12:30 PM", title: "Lunch", emoji: "🍽️", locationId: "loc-camp" },
    { id: "it-3", dayId: "day-today", time: "3:30 PM", title: "Afternoon Game Drive", emoji: "🐘", locationId: "loc-mara" },
    { id: "it-4", dayId: "day-today", time: "7:30 PM", title: "Dinner", emoji: "🔥", locationId: "loc-camp" },
    { id: "it-5", dayId: "day-2", time: "8:00 AM", title: "Drive to the Maasai Mara", emoji: "🚙", locationId: "loc-mara" },
    { id: "it-6", dayId: "day-1", time: "6:30 AM", title: "Sunrise Game Drive", emoji: "🌅", locationId: "loc-samburu" },
  ],
  guests: [
    { id: "g-sarah", tripId: "trip-africa-2026", name: "Sarah" },
    { id: "g-john", tripId: "trip-africa-2026", name: "John" },
    { id: "g-margaret", tripId: "trip-africa-2026", name: "Margaret" },
  ],
  memories: [
    {
      id: "m-1",
      tripId: "trip-africa-2026",
      guestId: "g-sarah",
      guestName: "Sarah",
      locationId: "loc-mara",
      locationName: "Maasai Mara",
      description: "What an incredible morning! Two lions resting right beside our vehicle.",
      photo: "lions",
      createdAt: "2026-08-11T07:40:00.000Z",
    },
    {
      id: "m-2",
      tripId: "trip-africa-2026",
      guestId: "g-john",
      guestName: "John",
      locationId: "loc-olpejeta",
      locationName: "Ol Pejeta",
      description: "The elephants walked right past us with Mount Kenya behind them. I will never forget it.",
      photo: "elephants",
      createdAt: "2026-08-08T16:10:00.000Z",
    },
    {
      id: "m-3",
      tripId: "trip-africa-2026",
      guestId: "g-margaret",
      guestName: "Margaret",
      locationId: "loc-naivasha",
      locationName: "Lake Naivasha",
      description: "Up before the sun for the balloon. Flamingos below us the whole way.",
      photo: "balloon",
      createdAt: "2026-08-10T05:30:00.000Z",
    },
  ],
  comments: [
    { id: "c-1", memoryId: "m-1", guestName: "Margaret", text: "Wonderful photograph, Sarah!", createdAt: "2026-08-11T08:00:00.000Z" },
    { id: "c-2", memoryId: "m-1", guestName: "John", text: "We were so lucky this morning.", createdAt: "2026-08-11T08:15:00.000Z" },
  ],
  likes: [
    { memoryId: "m-1", guestId: "g-john" },
    { memoryId: "m-1", guestId: "g-margaret" },
    { memoryId: "m-2", guestId: "g-sarah" },
  ],
  animals: [
    { id: "a-lion", name: "Lion", emoji: "🦁", category: "BIG FIVE" },
    { id: "a-elephant", name: "Elephant", emoji: "🐘", category: "BIG FIVE" },
    { id: "a-leopard", name: "Leopard", emoji: "🐆", category: "BIG FIVE" },
    { id: "a-rhino", name: "Rhino", emoji: "🦏", category: "BIG FIVE" },
    { id: "a-buffalo", name: "Buffalo", emoji: "🐃", category: "BIG FIVE" },
    { id: "a-giraffe", name: "Giraffe", emoji: "🦒", category: "OTHER WILDLIFE" },
    { id: "a-zebra", name: "Zebra", emoji: "🦓", category: "OTHER WILDLIFE" },
    { id: "a-hippo", name: "Hippo", emoji: "🦛", category: "OTHER WILDLIFE" },
    { id: "a-cheetah", name: "Cheetah", emoji: "🐆", category: "OTHER WILDLIFE" },
    { id: "a-wildebeest", name: "Wildebeest", emoji: "🐂", category: "OTHER WILDLIFE" },
    { id: "a-crocodile", name: "Crocodile", emoji: "🐊", category: "OTHER WILDLIFE" },
    { id: "a-warthog", name: "Warthog", emoji: "🐗", category: "OTHER WILDLIFE" },
    { id: "a-baboon", name: "Baboon", emoji: "🐒", category: "OTHER WILDLIFE" },
    { id: "a-ostrich", name: "Ostrich", emoji: "🦤", category: "BIRDS" },
    { id: "a-flamingo", name: "Flamingo", emoji: "🦩", category: "BIRDS" },
    { id: "a-eagle", name: "Fish Eagle", emoji: "🦅", category: "BIRDS" },
  ],
  sightings: [],
  words: [
    { id: "w-1", date: "2026-08-09", word: "JAMBO", meaning: "Hello", pronunciation: "JAM-boh" },
    { id: "w-2", date: "2026-08-10", word: "KARIBU", meaning: "Welcome", pronunciation: "kah-REE-boo" },
    { id: "w-3", date: TODAY_FALLBACK, word: "ASANTE", meaning: "Thank you", pronunciation: "ah-SAHN-teh" },
    { id: "w-4", date: "2026-08-12", word: "SIMBA", meaning: "Lion", pronunciation: "SEEM-bah" },
    { id: "w-5", date: "2026-08-13", word: "RAFIKI", meaning: "Friend", pronunciation: "rah-FEE-kee" },
    { id: "w-6", date: "2026-08-14", word: "SAFARI", meaning: "Journey", pronunciation: "sah-FAH-ree" },
    { id: "w-7", date: "2026-08-15", word: "KWAHERI", meaning: "Goodbye", pronunciation: "kwah-HEH-ree" },
  ],
  guides: [
    {
      id: "guide-1",
      tripId: "trip-africa-2026",
      name: "Daniel Mwangi",
      role: "Safari Guide",
      experience: "12 years of experience",
      phone: "+254712345678",
      whatsapp: "254712345678",
      about:
        "Daniel grew up beside the Mara and has guided Windsong groups for over a decade. He is always happy to help — just ask.",
      photo: "guide",
    },
  ],
  drivers: [
    {
      id: "driver-1",
      tripId: "trip-africa-2026",
      name: "Joseph Kimani",
      role: "Safari Driver",
      phone: "+254733112233",
      whatsapp: "254733112233",
      about: "Joseph has driven Windsong groups across Kenya for nine years.",
    },
  ],
  updates: [],
  syncQueue: [],
  visits: [],
  meGuestId: null,
};