/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddMemoryRouteImport } from './routes/add-memory'
import { Route as AnimalsRouteImport } from './routes/animals'
import { Route as FullJourneyRouteImport } from './routes/full-journey'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HomeRouteImport } from './routes/home'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as TodayRouteImport } from './routes/today'
import { Route as JSlugRouteImport } from './routes/j.$slug'
import { Route as JourneyIndexRouteImport } from './routes/journey.index'
import { Route as JourneyLocationIdRouteImport } from './routes/journey.$locationId'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as MemoriesMemoryIdRouteImport } from './routes/memories.$memoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMemoryRoute = AddMemoryRouteImport.update({
  id: '/add-memory',
  path: '/add-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsRoute = AnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const FullJourneyRoute = FullJourneyRouteImport.update({
  id: '/full-journey',
  path: '/full-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const JSlugRoute = JSlugRouteImport.update({
  id: '/j/$slug',
  path: '/j/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIndexRoute = JourneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyLocationIdRoute = JourneyLocationIdRouteImport.update({
  id: '/$locationId',
  path: '/$locationId',
  getParentRoute: () => JourneyRoute,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemoriesRoute,
} as any)
const MemoriesMemoryIdRoute = MemoriesMemoryIdRouteImport.update({
  id: '/$memoryId',
  path: '/$memoryId',
  getParentRoute: () => MemoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-memory': typeof AddMemoryRoute
  '/animals': typeof AnimalsRoute
  '/full-journey': typeof FullJourneyRoute
  '/guide': typeof GuideRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRouteWithChildren
  '/manager': typeof ManagerRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/staff': typeof StaffRoute
  '/staff-login': typeof StaffLoginRoute
  '/today': typeof TodayRoute
  '/j/$slug': typeof JSlugRoute
  '/journey/$locationId': typeof JourneyLocationIdRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/journey/': typeof JourneyIndexRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-memory': typeof AddMemoryRoute
  '/animals': typeof AnimalsRoute
  '/full-journey': typeof FullJourneyRoute
  '/guide': typeof GuideRoute
  '/home': typeof HomeRoute
  '/manager': typeof ManagerRoute
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/staff': typeof StaffRoute
  '/staff-login': typeof StaffLoginRoute
  '/today': typeof TodayRoute
  '/j/$slug': typeof JSlugRoute
  '/journey/$locationId': typeof JourneyLocationIdRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/journey': typeof JourneyIndexRoute
  '/memories': typeof MemoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-memory': typeof AddMemoryRoute
  '/animals': typeof AnimalsRoute
  '/full-journey': typeof FullJourneyRoute
  '/guide': typeof GuideRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRouteWithChildren
  '/manager': typeof ManagerRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/more': typeof MoreRoute
  '/profile': typeof ProfileRoute
  '/staff': typeof StaffRoute
  '/staff-login': typeof StaffLoginRoute
  '/today': typeof TodayRoute
  '/j/$slug': typeof JSlugRoute
  '/journey/$locationId': typeof JourneyLocationIdRoute
  '/memories/$memoryId': typeof MemoriesMemoryIdRoute
  '/journey/': typeof JourneyIndexRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-memory'
    | '/animals'
    | '/full-journey'
    | '/guide'
    | '/home'
    | '/journey'
    | '/manager'
    | '/memories'
    | '/more'
    | '/profile'
    | '/staff'
    | '/staff-login'
    | '/today'
    | '/j/$slug'
    | '/journey/$locationId'
    | '/memories/$memoryId'
    | '/journey/'
    | '/memories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-memory'
    | '/animals'
    | '/full-journey'
    | '/guide'
    | '/home'
    | '/manager'
    | '/more'
    | '/profile'
    | '/staff'
    | '/staff-login'
    | '/today'
    | '/j/$slug'
    | '/journey/$locationId'
    | '/memories/$memoryId'
    | '/journey'
    | '/memories'
  id:
    | '__root__'
    | '/'
    | '/add-memory'
    | '/animals'
    | '/full-journey'
    | '/guide'
    | '/home'
    | '/journey'
    | '/manager'
    | '/memories'
    | '/more'
    | '/profile'
    | '/staff'
    | '/staff-login'
    | '/today'
    | '/j/$slug'
    | '/journey/$locationId'
    | '/memories/$memoryId'
    | '/journey/'
    | '/memories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddMemoryRoute: typeof AddMemoryRoute
  AnimalsRoute: typeof AnimalsRoute
  FullJourneyRoute: typeof FullJourneyRoute
  GuideRoute: typeof GuideRoute
  HomeRoute: typeof HomeRoute
  JourneyRoute: typeof JourneyRouteWithChildren
  ManagerRoute: typeof ManagerRoute
  MemoriesRoute: typeof MemoriesRouteWithChildren
  MoreRoute: typeof MoreRoute
  ProfileRoute: typeof ProfileRoute
  StaffRoute: typeof StaffRoute
  StaffLoginRoute: typeof StaffLoginRoute
  TodayRoute: typeof TodayRoute
  JSlugRoute: typeof JSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-memory': {
      id: '/add-memory'
      path: '/add-memory'
      fullPath: '/add-memory'
      preLoaderRoute: typeof AddMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals': {
      id: '/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-journey': {
      id: '/full-journey'
      path: '/full-journey'
      fullPath: '/full-journey'
      preLoaderRoute: typeof FullJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/j/$slug': {
      id: '/j/$slug'
      path: '/j/$slug'
      fullPath: '/j/$slug'
      preLoaderRoute: typeof JSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/': {
      id: '/journey/'
      path: '/'
      fullPath: '/journey/'
      preLoaderRoute: typeof JourneyIndexRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/$locationId': {
      id: '/journey/$locationId'
      path: '/$locationId'
      fullPath: '/journey/$locationId'
      preLoaderRoute: typeof JourneyLocationIdRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/memories/': {
      id: '/memories/'
      path: '/'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/memories/$memoryId': {
      id: '/memories/$memoryId'
      path: '/$memoryId'
      fullPath: '/memories/$memoryId'
      preLoaderRoute: typeof MemoriesMemoryIdRouteImport
      parentRoute: typeof MemoriesRoute
    }
  }
}

interface JourneyRouteChildren {
  JourneyLocationIdRoute: typeof JourneyLocationIdRoute
  JourneyIndexRoute: typeof JourneyIndexRoute
}

const JourneyRouteChildren: JourneyRouteChildren = {
  JourneyLocationIdRoute: JourneyLocationIdRoute,
  JourneyIndexRoute: JourneyIndexRoute,
}

const JourneyRouteWithChildren =
  JourneyRoute._addFileChildren(JourneyRouteChildren)

interface MemoriesRouteChildren {
  MemoriesMemoryIdRoute: typeof MemoriesMemoryIdRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
}

const MemoriesRouteChildren: MemoriesRouteChildren = {
  MemoriesMemoryIdRoute: MemoriesMemoryIdRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
}

const MemoriesRouteWithChildren = MemoriesRoute._addFileChildren(
  MemoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddMemoryRoute: AddMemoryRoute,
  AnimalsRoute: AnimalsRoute,
  FullJourneyRoute: FullJourneyRoute,
  GuideRoute: GuideRoute,
  HomeRoute: HomeRoute,
  JourneyRoute: JourneyRouteWithChildren,
  ManagerRoute: ManagerRoute,
  MemoriesRoute: MemoriesRouteWithChildren,
  MoreRoute: MoreRoute,
  ProfileRoute: ProfileRoute,
  StaffRoute: StaffRoute,
  StaffLoginRoute: StaffLoginRoute,
  TodayRoute: TodayRoute,
  JSlugRoute: JSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
